# -*- coding: utf-8 -*-
"""Another copy of Tensors.ipynb - Toby Strawser

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tx7f3JE6ei8VfxX8OgR7Cv8jeFaIKiKH

<font color='red'>**Before you start, make a copy of this notebook! If you edit this one, you won't be able to save it and will lose all of your work!**</font>

# Overview

This assignment has you using NumPy operations to create and manipulate images. If you have a solid grasp of NumPy, including broadcasting and slicing, your code will be *very* short.

In each of cells below that contains the text `replace_this_with_your_code`, do so.

**This is an individual assignment. You are meant to write the code on your own. You are welcome to discuss *ideas* with other students (including on the class email list), but don't look at their code or show them yours.**

The cell below imports the necessary libraries.
"""

import numpy as np
import matplotlib.pyplot as plt

"""Define a 100x100 array `fig1` that has 1s on the top half and 0s on the bottom half."""

a = np.ones(shape=(50,100))
b = np.zeros(shape=(50,100))
fig1 = np.concatenate((a,b))
fig1

"""If your code worked, the code below will display a square that is yellow on the top half and purple on the bottom half.

(The expression `None` at the end of the cell prevents the notebook from printing the result returned by `imshow`.)
"""

plt.imshow(fig1)
None

"""Complete the function below. It should return `True` if the point `row, col` is within `radius` of `row_center, col_center`. Use the Pythagorean theorem."""

def within(row, col, row_center, col_center, radius):
  c = np.sqrt(((row - row_center) ** 2 ) + ((col - col_center)**2))
  return c < radius
#a^2 + b^2 = c^2

"""The cell below creates a 100x100 array of zeroes. It also defines two 100x100 arrays `r` and `c`, such that `r[i, j] == i` and `c[i, j] == c`. In other words, the value at any given point in `r` is the row coordinate of that point, and the value at any given point in `c` is the column coordinate of that point."""

fig2 = np.zeros((100, 100))
r, c = np.mgrid[:100, :100]

"""By calling `within`, set every element of `fig2` within 40 pixels of the point `50, 50` to 1. Because of the way NumPy handles arithmetic operations and allows Boolean arrays to be used for indexing, you can do this in one line."""

fig2[within(r,c,50,50,40) ] = 1

"""The code below should show a purple square with a yellow circle centered in it."""

plt.imshow(fig2)
None

"""Define another 100x100 image `fig3` that looks like a smiley face: a yellow circle with smaller purple circles for eyes and a purple rectangle for the mouth."""

fig3 = np.zeros((100,100))
r, c = np.mgrid[:100, :100]
fig3[within(r,c,50,50,40) ] = 1
fig3[within(r,c,35,35,5) ] = 0
fig3[within(r,c,35,60,5) ] = 0
fig3[60:70,35:60] = 0

plt.imshow(fig3)
None

"""The code below loads and displays an image of a river otter.

For this to work, you'll need to get [the image](https://upload.wikimedia.org/wikipedia/commons/5/52/Curious_Otter_at_Lake_Woodruff_National_Wildlife_Refuge_-_Flickr_-_Andrea_Westmoreland.jpg) and upload it to your notebook as `otter.jpg`. You don't have to hand in the image; I have it.

Image credit: By Andrea Westmoreland from DeLand, United States - Curious Otter at Lake Woodruff National Wildlife Refuge, CC BY-SA 2.0, https://commons.wikimedia.org/w/index.php?curid=26020201
"""

image = plt.imread('otter.jpg')
plt.imshow(image)
None

"""Make a copy of the image and replace the green and blue channels with zeroes. Display it."""

ott = image.copy()
ott.shape

ott[:,:,1:3] = 0

# for loop method that takes too long
# I wrote this before I remembered about array splicing
# for row in range(2500):
#   for col in range(2111):
#     for step in range(3):
#       if(step > 0):
#         ott[row,col,step] = 0
#need to go through and change the second and third element of each inner 'list' to a zero

plt.imshow(ott)

"""Make another copy of the original image and make it grayscale by taking the average across all three color channels. Display it."""

ott2 = image.copy()

ottGray = np.average(ott2, axis=2)[:,:, np.newaxis]
ott2[:, :, :] = ottGray.astype(ott2.dtype)

plt.imshow(ott2)

"""Display the negative (in the photographic sense) of the original image. If you are seeing some neon splotches near the whiskers and at the lower right of the otter, it's not quite right."""

ott3 = image.copy()

ott3[:, :, :] = 255 - ott3[:,:,:]

plt.imshow(ott3)

plt.imshow(image)

"""# Optional Challenge Problems

* Create and display a half-sized version of the otter image by keeping only the even-numbered pixels. It will look just as large but appear pixelated.
* Create and display a version of the otter image with four levels of gray.
"""

ott4 = image.copy()

'straw'[::2]

ott5 = ott4[::2,::2,:]
ott10 = ott4[::4, ::4,:]
ott20 = ott4[::8, ::8,:]
ott40 = ott4[::16, ::16,:]
ott5.shape

plt.imshow(ott5)

plt.imshow(ott10)

plt.imshow(ott20)

plt.imshow(ott40)

ott6 = image.copy()

ott6[( ott2[:,:,:] > 0 ) & (ott2[:,:,:] <= 85 ) ] = 0
ott6[( ott2[:,:,:] > 85) & (ott2[:,:,:] <= 170) ] = 85
ott6[( ott2[:,:,:] > 170) & (ott2[:,:,:] <= 254) ] = 170
ott6[( ott2[:,:,:] > 254) ] = 255

plt.imshow(ott6)

"""Demon otter lol

<font color='red'>**Remember to turn in your notebook in Google Classroom!**<font>
"""